# Generated by Django 2.1.3 on 2018-12-06 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20181201_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='die',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='roll',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='die',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roll',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
