# Generated by Django 2.1.3 on 2019-01-02 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_die_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='id',
        ),
        migrations.AddField(
            model_name='roll',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
