# Generated by Django 2.1.3 on 2019-01-03 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20190102_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='die',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roll',
            name='text',
        ),
        migrations.AddField(
            model_name='die',
            name='owner',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roll',
            name='owner',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
