# Generated by Django 2.1.3 on 2019-01-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20190103_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('faces', models.IntegerField(default=4)),
                ('result', models.IntegerField(default=0)),
                ('tally', models.IntegerField(default=0)),
            ],
        ),
    ]
