# Generated by Django 3.2.12 on 2024-07-03 14:39

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_tally'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.UUIDField()),
            ],
        ),
    ]
