# Generated by Django 3.2.12 on 2024-10-17 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_notation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('owner', models.UUIDField()),
            ],
        ),
    ]
